name: Java CI with Maven

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdkversion: [17]

    steps:
      - uses: actions/checkout@main

      - name: Cache Maven dependencies
        uses: actions/cache@main
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@main
        with:
          distribution: "temurin"
          java-version: ${{ matrix.jdkversion }}
          cache: "maven"

      - name: Build
        run: |
          rm -rf ~/.m2/repository/com/tcoded/FoliaLib
          rm -rf ~/.m2/repository/me/clip/placeholderapi
          mvn -V -B clean package

      - name: Get the repository name
        id: get-repo-name
        run: |
          echo "::set-output name=repo_name::$(echo ${{ github.repository }} | cut -d'/' -f2)"

      - name: Get short SHA
        id: sha
        run: |
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Upload Jar
        uses: actions/upload-artifact@main
        with:
          name: ${{ steps.get-repo-name.outputs.repo_name }}
          path: target/*.jar

      - name: Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.sha.outputs.short_sha }}
          prerelease: false
          title: "${{ steps.get-repo-name.outputs.repo_name }}-${{ steps.sha.outputs.short_sha }} Release"
          files: target/*.jar
